// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: v1/image/image.proto

package image

import (
	common "api-server/api/v1/common"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRequest) Reset() {
	*x = IdentityRequest{}
	mi := &file_v1_image_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRequest) ProtoMessage() {}

func (x *IdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_image_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRequest.ProtoReflect.Descriptor instead.
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return file_v1_image_image_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImageRepo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRepo) Reset() {
	*x = ImageRepo{}
	mi := &file_v1_image_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRepo) ProtoMessage() {}

func (x *ImageRepo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_image_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRepo.ProtoReflect.Descriptor instead.
func (*ImageRepo) Descriptor() ([]byte, []int) {
	return file_v1_image_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageRepo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImageRepo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageRepo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ImageRepo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ImageRepo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ImageRepo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListImageReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.Page           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImageReposRequest) Reset() {
	*x = ListImageReposRequest{}
	mi := &file_v1_image_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImageReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImageReposRequest) ProtoMessage() {}

func (x *ListImageReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_image_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImageReposRequest.ProtoReflect.Descriptor instead.
func (*ListImageReposRequest) Descriptor() ([]byte, []int) {
	return file_v1_image_image_proto_rawDescGZIP(), []int{2}
}

func (x *ListImageReposRequest) GetPage() *common.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListImageReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *common.Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items         []*ImageRepo           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImageReposResponse) Reset() {
	*x = ListImageReposResponse{}
	mi := &file_v1_image_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImageReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImageReposResponse) ProtoMessage() {}

func (x *ListImageReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_image_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImageReposResponse.ProtoReflect.Descriptor instead.
func (*ListImageReposResponse) Descriptor() ([]byte, []int) {
	return file_v1_image_image_proto_rawDescGZIP(), []int{3}
}

func (x *ListImageReposResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListImageReposResponse) GetItems() []*ImageRepo {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_v1_image_image_proto protoreflect.FileDescriptor

const file_v1_image_image_proto_rawDesc = "" +
	"\n" +
	"\x14v1/image/image.proto\x12\fapi.v1.image\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14v1/common/page.proto\x1a\x17validate/validate.proto\"4\n" +
	"\x0fIdentityRequest\x12!\n" +
	"\x04name\x18\x01 \x01(\tB\r\xe2A\x01\x02\xfaB\x06r\x04\x10\x01\x18@R\x04name\"\xa2\x02\n" +
	"\tImageRepo\x12!\n" +
	"\x04name\x18\x01 \x01(\tB\r\xe2A\x01\x02\xfaB\x06r\x04\x10\x01\x18@R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x03url\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\x03url\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12?\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\tcreatedAt\x12?\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\tupdatedAt\"@\n" +
	"\x15ListImageReposRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.api.v1.common.PageR\x04page\"\x82\x01\n" +
	"\x16ListImageReposResponse\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.api.v1.common.PaginationR\n" +
	"pagination\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.api.v1.image.ImageRepoR\x05items2\xac\x04\n" +
	"\fImageService\x12i\n" +
	"\fGetImageRepo\x12\x1d.api.v1.image.IdentityRequest\x1a\x17.api.v1.image.ImageRepo\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/image/repo/{name}\x12w\n" +
	"\x0eListImageRepos\x12#.api.v1.image.ListImageReposRequest\x1a$.api.v1.image.ListImageReposResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/image/repo\x12a\n" +
	"\x0fCreateImageRepo\x12\x17.api.v1.image.ImageRepo\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/image/repo\x12h\n" +
	"\x0fUpdateImageRepo\x12\x17.api.v1.image.ImageRepo\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/v1/image/repo/{name}\x12k\n" +
	"\x0fDeleteImageRepo\x12\x1d.api.v1.image.IdentityRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/v1/image/repo/{name}B\x1fZ\x1dapi-server/api/v1/image;imageb\x06proto3"

var (
	file_v1_image_image_proto_rawDescOnce sync.Once
	file_v1_image_image_proto_rawDescData []byte
)

func file_v1_image_image_proto_rawDescGZIP() []byte {
	file_v1_image_image_proto_rawDescOnce.Do(func() {
		file_v1_image_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_image_image_proto_rawDesc), len(file_v1_image_image_proto_rawDesc)))
	})
	return file_v1_image_image_proto_rawDescData
}

var file_v1_image_image_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_image_image_proto_goTypes = []any{
	(*IdentityRequest)(nil),        // 0: api.v1.image.IdentityRequest
	(*ImageRepo)(nil),              // 1: api.v1.image.ImageRepo
	(*ListImageReposRequest)(nil),  // 2: api.v1.image.ListImageReposRequest
	(*ListImageReposResponse)(nil), // 3: api.v1.image.ListImageReposResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
	(*common.Page)(nil),            // 5: api.v1.common.Page
	(*common.Pagination)(nil),      // 6: api.v1.common.Pagination
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_v1_image_image_proto_depIdxs = []int32{
	4,  // 0: api.v1.image.ImageRepo.created_at:type_name -> google.protobuf.Timestamp
	4,  // 1: api.v1.image.ImageRepo.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: api.v1.image.ListImageReposRequest.page:type_name -> api.v1.common.Page
	6,  // 3: api.v1.image.ListImageReposResponse.pagination:type_name -> api.v1.common.Pagination
	1,  // 4: api.v1.image.ListImageReposResponse.items:type_name -> api.v1.image.ImageRepo
	0,  // 5: api.v1.image.ImageService.GetImageRepo:input_type -> api.v1.image.IdentityRequest
	2,  // 6: api.v1.image.ImageService.ListImageRepos:input_type -> api.v1.image.ListImageReposRequest
	1,  // 7: api.v1.image.ImageService.CreateImageRepo:input_type -> api.v1.image.ImageRepo
	1,  // 8: api.v1.image.ImageService.UpdateImageRepo:input_type -> api.v1.image.ImageRepo
	0,  // 9: api.v1.image.ImageService.DeleteImageRepo:input_type -> api.v1.image.IdentityRequest
	1,  // 10: api.v1.image.ImageService.GetImageRepo:output_type -> api.v1.image.ImageRepo
	3,  // 11: api.v1.image.ImageService.ListImageRepos:output_type -> api.v1.image.ListImageReposResponse
	7,  // 12: api.v1.image.ImageService.CreateImageRepo:output_type -> google.protobuf.Empty
	7,  // 13: api.v1.image.ImageService.UpdateImageRepo:output_type -> google.protobuf.Empty
	7,  // 14: api.v1.image.ImageService.DeleteImageRepo:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_image_image_proto_init() }
func file_v1_image_image_proto_init() {
	if File_v1_image_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_image_image_proto_rawDesc), len(file_v1_image_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_image_image_proto_goTypes,
		DependencyIndexes: file_v1_image_image_proto_depIdxs,
		MessageInfos:      file_v1_image_image_proto_msgTypes,
	}.Build()
	File_v1_image_image_proto = out.File
	file_v1_image_image_proto_goTypes = nil
	file_v1_image_image_proto_depIdxs = nil
}
