// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v1/image/image.proto

package image

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageService_GetImageRepo_FullMethodName    = "/api.v1.image.ImageService/GetImageRepo"
	ImageService_ListImageRepos_FullMethodName  = "/api.v1.image.ImageService/ListImageRepos"
	ImageService_CreateImageRepo_FullMethodName = "/api.v1.image.ImageService/CreateImageRepo"
	ImageService_UpdateImageRepo_FullMethodName = "/api.v1.image.ImageService/UpdateImageRepo"
	ImageService_DeleteImageRepo_FullMethodName = "/api.v1.image.ImageService/DeleteImageRepo"
)

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	GetImageRepo(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*ImageRepo, error)
	ListImageRepos(ctx context.Context, in *ListImageReposRequest, opts ...grpc.CallOption) (*ListImageReposResponse, error)
	CreateImageRepo(ctx context.Context, in *ImageRepo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateImageRepo(ctx context.Context, in *ImageRepo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteImageRepo(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) GetImageRepo(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*ImageRepo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageRepo)
	err := c.cc.Invoke(ctx, ImageService_GetImageRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) ListImageRepos(ctx context.Context, in *ListImageReposRequest, opts ...grpc.CallOption) (*ListImageReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImageReposResponse)
	err := c.cc.Invoke(ctx, ImageService_ListImageRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) CreateImageRepo(ctx context.Context, in *ImageRepo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ImageService_CreateImageRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) UpdateImageRepo(ctx context.Context, in *ImageRepo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ImageService_UpdateImageRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) DeleteImageRepo(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ImageService_DeleteImageRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility.
type ImageServiceServer interface {
	GetImageRepo(context.Context, *IdentityRequest) (*ImageRepo, error)
	ListImageRepos(context.Context, *ListImageReposRequest) (*ListImageReposResponse, error)
	CreateImageRepo(context.Context, *ImageRepo) (*emptypb.Empty, error)
	UpdateImageRepo(context.Context, *ImageRepo) (*emptypb.Empty, error)
	DeleteImageRepo(context.Context, *IdentityRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageServiceServer struct{}

func (UnimplementedImageServiceServer) GetImageRepo(context.Context, *IdentityRequest) (*ImageRepo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageRepo not implemented")
}
func (UnimplementedImageServiceServer) ListImageRepos(context.Context, *ListImageReposRequest) (*ListImageReposResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImageRepos not implemented")
}
func (UnimplementedImageServiceServer) CreateImageRepo(context.Context, *ImageRepo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateImageRepo not implemented")
}
func (UnimplementedImageServiceServer) UpdateImageRepo(context.Context, *ImageRepo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateImageRepo not implemented")
}
func (UnimplementedImageServiceServer) DeleteImageRepo(context.Context, *IdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImageRepo not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}
func (UnimplementedImageServiceServer) testEmbeddedByValue()                      {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	// If the following call pancis, it indicates UnimplementedImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageService_ServiceDesc, srv)
}

func _ImageService_GetImageRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).GetImageRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_GetImageRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).GetImageRepo(ctx, req.(*IdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_ListImageRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImageReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ListImageRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_ListImageRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ListImageRepos(ctx, req.(*ListImageReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_CreateImageRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRepo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).CreateImageRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_CreateImageRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).CreateImageRepo(ctx, req.(*ImageRepo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_UpdateImageRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRepo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).UpdateImageRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_UpdateImageRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).UpdateImageRepo(ctx, req.(*ImageRepo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_DeleteImageRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).DeleteImageRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_DeleteImageRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).DeleteImageRepo(ctx, req.(*IdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageService_ServiceDesc is the grpc.ServiceDesc for ImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.image.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImageRepo",
			Handler:    _ImageService_GetImageRepo_Handler,
		},
		{
			MethodName: "ListImageRepos",
			Handler:    _ImageService_ListImageRepos_Handler,
		},
		{
			MethodName: "CreateImageRepo",
			Handler:    _ImageService_CreateImageRepo_Handler,
		},
		{
			MethodName: "UpdateImageRepo",
			Handler:    _ImageService_UpdateImageRepo_Handler,
		},
		{
			MethodName: "DeleteImageRepo",
			Handler:    _ImageService_DeleteImageRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/image/image.proto",
}
