/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	applicationv1 "api-server/internal/kube/apis/application/v1"
	applyconfigurationapplicationv1 "api-server/internal/kube/applyconfiguration/application/v1"
	scheme "api-server/internal/kube/clientset/versioned/scheme"
	context "context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ApplicationsGetter has a method to return a ApplicationInterface.
// A group's client should implement this interface.
type ApplicationsGetter interface {
	Applications(namespace string) ApplicationInterface
}

// ApplicationInterface has methods to work with Application resources.
type ApplicationInterface interface {
	Create(ctx context.Context, application *applicationv1.Application, opts metav1.CreateOptions) (*applicationv1.Application, error)
	Update(ctx context.Context, application *applicationv1.Application, opts metav1.UpdateOptions) (*applicationv1.Application, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, application *applicationv1.Application, opts metav1.UpdateOptions) (*applicationv1.Application, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*applicationv1.Application, error)
	List(ctx context.Context, opts metav1.ListOptions) (*applicationv1.ApplicationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *applicationv1.Application, err error)
	Apply(ctx context.Context, application *applyconfigurationapplicationv1.ApplicationApplyConfiguration, opts metav1.ApplyOptions) (result *applicationv1.Application, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, application *applyconfigurationapplicationv1.ApplicationApplyConfiguration, opts metav1.ApplyOptions) (result *applicationv1.Application, err error)
	GetApplication(ctx context.Context, name string, opts metav1.GetOptions) (*applicationv1.Application, error)

	ApplicationExpansion
}

// applications implements ApplicationInterface
type applications struct {
	*gentype.ClientWithListAndApply[*applicationv1.Application, *applicationv1.ApplicationList, *applyconfigurationapplicationv1.ApplicationApplyConfiguration]
}

// newApplications returns a Applications
func newApplications(c *KubelandV1Client, namespace string) *applications {
	return &applications{
		gentype.NewClientWithListAndApply[*applicationv1.Application, *applicationv1.ApplicationList, *applyconfigurationapplicationv1.ApplicationApplyConfiguration](
			"applications",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *applicationv1.Application { return &applicationv1.Application{} },
			func() *applicationv1.ApplicationList { return &applicationv1.ApplicationList{} },
		),
	}
}

// GetApplication takes name of the application, and returns the corresponding application object, and an error if there is any.
func (c *applications) GetApplication(ctx context.Context, name string, options metav1.GetOptions) (result *applicationv1.Application, err error) {
	result = &applicationv1.Application{}
	err = c.GetClient().Get().
		Namespace(c.GetNamespace()).
		Resource("applications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
