apiVersion: app.kubeland.com/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: 
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  # TODO(user): Add fields here
