// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: v1/common/page.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_v1_common_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_v1_common_page_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Page) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_v1_common_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1_common_page_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Pagination) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_v1_common_page_proto protoreflect.FileDescriptor

const file_v1_common_page_proto_rawDesc = "" +
	"\n" +
	"\x14v1/common/page.proto\x12\rapi.v1.common\"4\n" +
	"\x04Page\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"P\n" +
	"\n" +
	"Pagination\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05totalB!Z\x1fapi-server/api/v1/common;commonb\x06proto3"

var (
	file_v1_common_page_proto_rawDescOnce sync.Once
	file_v1_common_page_proto_rawDescData []byte
)

func file_v1_common_page_proto_rawDescGZIP() []byte {
	file_v1_common_page_proto_rawDescOnce.Do(func() {
		file_v1_common_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_page_proto_rawDesc), len(file_v1_common_page_proto_rawDesc)))
	})
	return file_v1_common_page_proto_rawDescData
}

var file_v1_common_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_common_page_proto_goTypes = []any{
	(*Page)(nil),       // 0: api.v1.common.Page
	(*Pagination)(nil), // 1: api.v1.common.Pagination
}
var file_v1_common_page_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_common_page_proto_init() }
func file_v1_common_page_proto_init() {
	if File_v1_common_page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_page_proto_rawDesc), len(file_v1_common_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_page_proto_goTypes,
		DependencyIndexes: file_v1_common_page_proto_depIdxs,
		MessageInfos:      file_v1_common_page_proto_msgTypes,
	}.Build()
	File_v1_common_page_proto = out.File
	file_v1_common_page_proto_goTypes = nil
	file_v1_common_page_proto_depIdxs = nil
}
