// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: v1/application/application.proto

package application

import (
	_ "api-server/api/v1/common"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     uint64                 `protobuf:"varint,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_v1_application_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_v1_application_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_v1_application_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Application) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_v1_application_application_proto protoreflect.FileDescriptor

const file_v1_application_application_proto_rawDesc = "" +
	"\n" +
	" v1/application/application.proto\x12\x12api.v1.application\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a\x14v1/common/page.proto\"\xa0\x01\n" +
	"\vApplication\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x04B\x04\xe2A\x01\x05R\x02id\x12*\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\x04B\v\xe2A\x01\x02\xfaB\x042\x02 \x00R\tclusterId\x12\x1f\n" +
	"\x04name\x18\x03 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x18@R\x04name\x12.\n" +
	"\vdescription\x18\x04 \x01(\tB\f\xe2A\x01\x01\xfaB\x05r\x03\x18\x80\x04R\vdescription2\x82\x01\n" +
	"\x12ApplicationService\x12l\n" +
	"\x11CreateApplication\x12\x1f.api.v1.application.Application\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/applicationB+Z)api-server/api/v1/application;applicationb\x06proto3"

var (
	file_v1_application_application_proto_rawDescOnce sync.Once
	file_v1_application_application_proto_rawDescData []byte
)

func file_v1_application_application_proto_rawDescGZIP() []byte {
	file_v1_application_application_proto_rawDescOnce.Do(func() {
		file_v1_application_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_application_application_proto_rawDesc), len(file_v1_application_application_proto_rawDesc)))
	})
	return file_v1_application_application_proto_rawDescData
}

var file_v1_application_application_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_application_application_proto_goTypes = []any{
	(*Application)(nil),   // 0: api.v1.application.Application
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_v1_application_application_proto_depIdxs = []int32{
	0, // 0: api.v1.application.ApplicationService.CreateApplication:input_type -> api.v1.application.Application
	1, // 1: api.v1.application.ApplicationService.CreateApplication:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_application_application_proto_init() }
func file_v1_application_application_proto_init() {
	if File_v1_application_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_application_application_proto_rawDesc), len(file_v1_application_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_application_application_proto_goTypes,
		DependencyIndexes: file_v1_application_application_proto_depIdxs,
		MessageInfos:      file_v1_application_application_proto_msgTypes,
	}.Build()
	File_v1_application_application_proto = out.File
	file_v1_application_application_proto_goTypes = nil
	file_v1_application_application_proto_depIdxs = nil
}
