// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: v1/application/application.proto

package application

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationApplicationServiceCreateApplication = "/api.v1.application.ApplicationService/CreateApplication"

type ApplicationServiceHTTPServer interface {
	CreateApplication(context.Context, *Application) (*emptypb.Empty, error)
}

func RegisterApplicationServiceHTTPServer(s *http.Server, srv ApplicationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/application", _ApplicationService_CreateApplication0_HTTP_Handler(srv))
}

func _ApplicationService_CreateApplication0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Application
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceCreateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApplication(ctx, req.(*Application))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ApplicationServiceHTTPClient interface {
	CreateApplication(ctx context.Context, req *Application, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type ApplicationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewApplicationServiceHTTPClient(client *http.Client) ApplicationServiceHTTPClient {
	return &ApplicationServiceHTTPClientImpl{client}
}

func (c *ApplicationServiceHTTPClientImpl) CreateApplication(ctx context.Context, in *Application, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/application"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationServiceCreateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
