// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: v1/build_task/build_task.proto

package task

import (
	application "api-server/api/v1/application"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED          Status = 0
	Status_STATUS_RUNNING              Status = 1
	Status_STATUS_COMPLETE             Status = 2
	Status_STATUS_FAILED               Status = 3
	Status_STATUS_SUSPENDED            Status = 4
	Status_STATUS_FAILURE_TARGET       Status = 5
	Status_STATUS_SUCCESS_CRITERIA_MET Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_RUNNING",
		2: "STATUS_COMPLETE",
		3: "STATUS_FAILED",
		4: "STATUS_SUSPENDED",
		5: "STATUS_FAILURE_TARGET",
		6: "STATUS_SUCCESS_CRITERIA_MET",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":          0,
		"STATUS_RUNNING":              1,
		"STATUS_COMPLETE":             2,
		"STATUS_FAILED":               3,
		"STATUS_SUSPENDED":            4,
		"STATUS_FAILURE_TARGET":       5,
		"STATUS_SUCCESS_CRITERIA_MET": 6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_build_task_build_task_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_v1_build_task_build_task_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_v1_build_task_build_task_proto_rawDescGZIP(), []int{0}
}

type BuildTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.build.task.Status" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTask) Reset() {
	*x = BuildTask{}
	mi := &file_v1_build_task_build_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTask) ProtoMessage() {}

func (x *BuildTask) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_task_build_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTask.ProtoReflect.Descriptor instead.
func (*BuildTask) Descriptor() ([]byte, []int) {
	return file_v1_build_task_build_task_proto_rawDescGZIP(), []int{0}
}

func (x *BuildTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildTask) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *BuildTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateBuildTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildTaskRequest) Reset() {
	*x = CreateBuildTaskRequest{}
	mi := &file_v1_build_task_build_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildTaskRequest) ProtoMessage() {}

func (x *CreateBuildTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_task_build_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildTaskRequest) Descriptor() ([]byte, []int) {
	return file_v1_build_task_build_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBuildTaskRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateBuildTaskRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type ListBuildTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BuildTask           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildTaskResponse) Reset() {
	*x = ListBuildTaskResponse{}
	mi := &file_v1_build_task_build_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildTaskResponse) ProtoMessage() {}

func (x *ListBuildTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_task_build_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildTaskResponse.ProtoReflect.Descriptor instead.
func (*ListBuildTaskResponse) Descriptor() ([]byte, []int) {
	return file_v1_build_task_build_task_proto_rawDescGZIP(), []int{2}
}

func (x *ListBuildTaskResponse) GetItems() []*BuildTask {
	if x != nil {
		return x.Items
	}
	return nil
}

type IdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	JobName       string                 `protobuf:"bytes,2,opt,name=jobName,proto3" json:"jobName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRequest) Reset() {
	*x = IdentityRequest{}
	mi := &file_v1_build_task_build_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRequest) ProtoMessage() {}

func (x *IdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_task_build_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRequest.ProtoReflect.Descriptor instead.
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return file_v1_build_task_build_task_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *IdentityRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

var File_v1_build_task_build_task_proto protoreflect.FileDescriptor

const file_v1_build_task_build_task_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/build_task/build_task.proto\x12\x11api.v1.build.task\x1a v1/application/application.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x8d\x01\n" +
	"\tBuildTask\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.api.v1.build.task.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"V\n" +
	"\x16CreateBuildTaskRequest\x12\x1e\n" +
	"\aappName\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aappName\x12\x1c\n" +
	"\x06commit\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x06commit\"K\n" +
	"\x15ListBuildTaskResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.api.v1.build.task.BuildTaskR\x05items\"Q\n" +
	"\x0fIdentityRequest\x12\x1e\n" +
	"\aappName\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aappName\x12\x1e\n" +
	"\ajobName\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\ajobName*\xae\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_COMPLETE\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04\x12\x19\n" +
	"\x15STATUS_FAILURE_TARGET\x10\x05\x12\x1f\n" +
	"\x1bSTATUS_SUCCESS_CRITERIA_MET\x10\x062\x8a\x02\n" +
	"\x10BuildTaskService\x12x\n" +
	"\x06Create\x12).api.v1.build.task.CreateBuildTaskRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/app/{appName}/build/task\x12|\n" +
	"\x04List\x12#.api.v1.application.IdentityRequest\x1a(.api.v1.build.task.ListBuildTaskResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/app/{name}/build/taskB#Z!api-server/api/v1/build/task;taskb\x06proto3"

var (
	file_v1_build_task_build_task_proto_rawDescOnce sync.Once
	file_v1_build_task_build_task_proto_rawDescData []byte
)

func file_v1_build_task_build_task_proto_rawDescGZIP() []byte {
	file_v1_build_task_build_task_proto_rawDescOnce.Do(func() {
		file_v1_build_task_build_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_build_task_build_task_proto_rawDesc), len(file_v1_build_task_build_task_proto_rawDesc)))
	})
	return file_v1_build_task_build_task_proto_rawDescData
}

var file_v1_build_task_build_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_build_task_build_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_build_task_build_task_proto_goTypes = []any{
	(Status)(0),                         // 0: api.v1.build.task.Status
	(*BuildTask)(nil),                   // 1: api.v1.build.task.BuildTask
	(*CreateBuildTaskRequest)(nil),      // 2: api.v1.build.task.CreateBuildTaskRequest
	(*ListBuildTaskResponse)(nil),       // 3: api.v1.build.task.ListBuildTaskResponse
	(*IdentityRequest)(nil),             // 4: api.v1.build.task.IdentityRequest
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
	(*application.IdentityRequest)(nil), // 6: api.v1.application.IdentityRequest
	(*emptypb.Empty)(nil),               // 7: google.protobuf.Empty
}
var file_v1_build_task_build_task_proto_depIdxs = []int32{
	0, // 0: api.v1.build.task.BuildTask.status:type_name -> api.v1.build.task.Status
	5, // 1: api.v1.build.task.BuildTask.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: api.v1.build.task.ListBuildTaskResponse.items:type_name -> api.v1.build.task.BuildTask
	2, // 3: api.v1.build.task.BuildTaskService.Create:input_type -> api.v1.build.task.CreateBuildTaskRequest
	6, // 4: api.v1.build.task.BuildTaskService.List:input_type -> api.v1.application.IdentityRequest
	7, // 5: api.v1.build.task.BuildTaskService.Create:output_type -> google.protobuf.Empty
	3, // 6: api.v1.build.task.BuildTaskService.List:output_type -> api.v1.build.task.ListBuildTaskResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_build_task_build_task_proto_init() }
func file_v1_build_task_build_task_proto_init() {
	if File_v1_build_task_build_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_build_task_build_task_proto_rawDesc), len(file_v1_build_task_build_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_build_task_build_task_proto_goTypes,
		DependencyIndexes: file_v1_build_task_build_task_proto_depIdxs,
		EnumInfos:         file_v1_build_task_build_task_proto_enumTypes,
		MessageInfos:      file_v1_build_task_build_task_proto_msgTypes,
	}.Build()
	File_v1_build_task_build_task_proto = out.File
	file_v1_build_task_build_task_proto_goTypes = nil
	file_v1_build_task_build_task_proto_depIdxs = nil
}
