// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v1/build_task/build_task.proto

package task

import (
	application "api-server/api/v1/application"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildTaskService_Create_FullMethodName = "/api.v1.build.task.BuildTaskService/Create"
)

// BuildTaskServiceClient is the client API for BuildTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildTaskServiceClient interface {
	Create(ctx context.Context, in *application.IdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type buildTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildTaskServiceClient(cc grpc.ClientConnInterface) BuildTaskServiceClient {
	return &buildTaskServiceClient{cc}
}

func (c *buildTaskServiceClient) Create(ctx context.Context, in *application.IdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BuildTaskService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildTaskServiceServer is the server API for BuildTaskService service.
// All implementations must embed UnimplementedBuildTaskServiceServer
// for forward compatibility.
type BuildTaskServiceServer interface {
	Create(context.Context, *application.IdentityRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBuildTaskServiceServer()
}

// UnimplementedBuildTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildTaskServiceServer struct{}

func (UnimplementedBuildTaskServiceServer) Create(context.Context, *application.IdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBuildTaskServiceServer) mustEmbedUnimplementedBuildTaskServiceServer() {}
func (UnimplementedBuildTaskServiceServer) testEmbeddedByValue()                          {}

// UnsafeBuildTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildTaskServiceServer will
// result in compilation errors.
type UnsafeBuildTaskServiceServer interface {
	mustEmbedUnimplementedBuildTaskServiceServer()
}

func RegisterBuildTaskServiceServer(s grpc.ServiceRegistrar, srv BuildTaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedBuildTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildTaskService_ServiceDesc, srv)
}

func _BuildTaskService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(application.IdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildTaskServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildTaskService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildTaskServiceServer).Create(ctx, req.(*application.IdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildTaskService_ServiceDesc is the grpc.ServiceDesc for BuildTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.build.task.BuildTaskService",
	HandlerType: (*BuildTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BuildTaskService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/build_task/build_task.proto",
}
