// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-server/internal/biz"
	"api-server/internal/conf"
	"api-server/internal/data"
	"api-server/internal/server"
	"api-server/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	clusterBiz := biz.NewClusterBiz(dataData)
	clusterService := service.NewClusterService(clusterBiz)
	v := service.NewServices(clusterService)
	grpcServer := server.NewGRPCServer(bootstrap)
	httpServer := server.NewHTTPServer(bootstrap)
	app := newApp(logger, v, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
