// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: v1/build_settings/build_settings.proto

package settings

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId uint64                 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_v1_build_settings_build_settings_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

type BuildSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId uint64                 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Dockerfile    string                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSettings) Reset() {
	*x = BuildSettings{}
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSettings) ProtoMessage() {}

func (x *BuildSettings) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSettings.ProtoReflect.Descriptor instead.
func (*BuildSettings) Descriptor() ([]byte, []int) {
	return file_v1_build_settings_build_settings_proto_rawDescGZIP(), []int{1}
}

func (x *BuildSettings) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *BuildSettings) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

type GitSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSettings) Reset() {
	*x = GitSettings{}
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSettings) ProtoMessage() {}

func (x *GitSettings) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSettings.ProtoReflect.Descriptor instead.
func (*GitSettings) Descriptor() ([]byte, []int) {
	return file_v1_build_settings_build_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GitSettings) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_v1_build_settings_build_settings_proto protoreflect.FileDescriptor

const file_v1_build_settings_build_settings_proto_rawDesc = "" +
	"\n" +
	"&v1/build_settings/build_settings.proto\x12\x15api.v1.build.settings\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"8\n" +
	"\tIdRequest\x12+\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04B\x04\xe2A\x01\x02R\rapplicationId\"b\n" +
	"\rBuildSettings\x12+\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04B\x04\xe2A\x01\x02R\rapplicationId\x12$\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\n" +
	"dockerfile\"/\n" +
	"\vGitSettings\x12 \n" +
	"\x03url\x18\x01 \x01(\tB\x0e\xe2A\x01\x02\xfaB\ar\x05\x10\x01\x18\x80\x04R\x03url2\xa5\x02\n" +
	"\x14BuildSettingsService\x12\x87\x01\n" +
	"\x10GetBuildSettings\x12 .api.v1.build.settings.IdRequest\x1a$.api.v1.build.settings.BuildSettings\"+\x82\xd3\xe4\x93\x02%\x12#/v1/build/settings/{application_id}\x12\x82\x01\n" +
	"\x12ApplyBuildSettings\x12$.api.v1.build.settings.BuildSettings\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/build/settings/{application_id}B+Z)api-server/api/v1/build/settings;settingsb\x06proto3"

var (
	file_v1_build_settings_build_settings_proto_rawDescOnce sync.Once
	file_v1_build_settings_build_settings_proto_rawDescData []byte
)

func file_v1_build_settings_build_settings_proto_rawDescGZIP() []byte {
	file_v1_build_settings_build_settings_proto_rawDescOnce.Do(func() {
		file_v1_build_settings_build_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_build_settings_build_settings_proto_rawDesc), len(file_v1_build_settings_build_settings_proto_rawDesc)))
	})
	return file_v1_build_settings_build_settings_proto_rawDescData
}

var file_v1_build_settings_build_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_build_settings_build_settings_proto_goTypes = []any{
	(*IdRequest)(nil),     // 0: api.v1.build.settings.IdRequest
	(*BuildSettings)(nil), // 1: api.v1.build.settings.BuildSettings
	(*GitSettings)(nil),   // 2: api.v1.build.settings.GitSettings
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_v1_build_settings_build_settings_proto_depIdxs = []int32{
	0, // 0: api.v1.build.settings.BuildSettingsService.GetBuildSettings:input_type -> api.v1.build.settings.IdRequest
	1, // 1: api.v1.build.settings.BuildSettingsService.ApplyBuildSettings:input_type -> api.v1.build.settings.BuildSettings
	1, // 2: api.v1.build.settings.BuildSettingsService.GetBuildSettings:output_type -> api.v1.build.settings.BuildSettings
	3, // 3: api.v1.build.settings.BuildSettingsService.ApplyBuildSettings:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_build_settings_build_settings_proto_init() }
func file_v1_build_settings_build_settings_proto_init() {
	if File_v1_build_settings_build_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_build_settings_build_settings_proto_rawDesc), len(file_v1_build_settings_build_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_build_settings_build_settings_proto_goTypes,
		DependencyIndexes: file_v1_build_settings_build_settings_proto_depIdxs,
		MessageInfos:      file_v1_build_settings_build_settings_proto_msgTypes,
	}.Build()
	File_v1_build_settings_build_settings_proto = out.File
	file_v1_build_settings_build_settings_proto_goTypes = nil
	file_v1_build_settings_build_settings_proto_depIdxs = nil
}
