// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: v1/build_settings/build_settings.proto

package settings

import (
	application "api-server/api/v1/application"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildSettings struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Git           *BuildSettings_GitSettings   `protobuf:"bytes,1,opt,name=git,proto3" json:"git,omitempty"`
	Image         *BuildSettings_ImageSettings `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Dockerfile    string                       `protobuf:"bytes,3,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSettings) Reset() {
	*x = BuildSettings{}
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSettings) ProtoMessage() {}

func (x *BuildSettings) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSettings.ProtoReflect.Descriptor instead.
func (*BuildSettings) Descriptor() ([]byte, []int) {
	return file_v1_build_settings_build_settings_proto_rawDescGZIP(), []int{0}
}

func (x *BuildSettings) GetGit() *BuildSettings_GitSettings {
	if x != nil {
		return x.Git
	}
	return nil
}

func (x *BuildSettings) GetImage() *BuildSettings_ImageSettings {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *BuildSettings) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

type ApplyBuildSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BuildSettings *BuildSettings         `protobuf:"bytes,2,opt,name=build_settings,json=buildSettings,proto3" json:"build_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyBuildSettingsRequest) Reset() {
	*x = ApplyBuildSettingsRequest{}
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBuildSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBuildSettingsRequest) ProtoMessage() {}

func (x *ApplyBuildSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBuildSettingsRequest.ProtoReflect.Descriptor instead.
func (*ApplyBuildSettingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_build_settings_build_settings_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyBuildSettingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyBuildSettingsRequest) GetBuildSettings() *BuildSettings {
	if x != nil {
		return x.BuildSettings
	}
	return nil
}

type BuildSettings_GitSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSettings_GitSettings) Reset() {
	*x = BuildSettings_GitSettings{}
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSettings_GitSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSettings_GitSettings) ProtoMessage() {}

func (x *BuildSettings_GitSettings) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSettings_GitSettings.ProtoReflect.Descriptor instead.
func (*BuildSettings_GitSettings) Descriptor() ([]byte, []int) {
	return file_v1_build_settings_build_settings_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BuildSettings_GitSettings) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type BuildSettings_ImageSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSettings_ImageSettings) Reset() {
	*x = BuildSettings_ImageSettings{}
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSettings_ImageSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSettings_ImageSettings) ProtoMessage() {}

func (x *BuildSettings_ImageSettings) ProtoReflect() protoreflect.Message {
	mi := &file_v1_build_settings_build_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSettings_ImageSettings.ProtoReflect.Descriptor instead.
func (*BuildSettings_ImageSettings) Descriptor() ([]byte, []int) {
	return file_v1_build_settings_build_settings_proto_rawDescGZIP(), []int{0, 1}
}

func (x *BuildSettings_ImageSettings) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_v1_build_settings_build_settings_proto protoreflect.FileDescriptor

const file_v1_build_settings_build_settings_proto_rawDesc = "" +
	"\n" +
	"&v1/build_settings/build_settings.proto\x12\x15api.v1.build.settings\x1a v1/application/application.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"\xb3\x02\n" +
	"\rBuildSettings\x12H\n" +
	"\x03git\x18\x01 \x01(\v20.api.v1.build.settings.BuildSettings.GitSettingsB\x04\xe2A\x01\x02R\x03git\x12N\n" +
	"\x05image\x18\x02 \x01(\v22.api.v1.build.settings.BuildSettings.ImageSettingsB\x04\xe2A\x01\x02R\x05image\x12$\n" +
	"\n" +
	"dockerfile\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\n" +
	"dockerfile\x1a/\n" +
	"\vGitSettings\x12 \n" +
	"\x03url\x18\x01 \x01(\tB\x0e\xe2A\x01\x02\xfaB\ar\x05\x10\x01\x18\x80\x04R\x03url\x1a1\n" +
	"\rImageSettings\x12 \n" +
	"\x03url\x18\x01 \x01(\tB\x0e\xe2A\x01\x02\xfaB\ar\x05\x10\x01\x18\x80\x04R\x03url\"\x82\x01\n" +
	"\x19ApplyBuildSettingsRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12K\n" +
	"\x0ebuild_settings\x18\x02 \x01(\v2$.api.v1.build.settings.BuildSettingsR\rbuildSettings2\xb5\x02\n" +
	"\x14BuildSettingsService\x12\x84\x01\n" +
	"\x10GetBuildSettings\x12#.api.v1.application.IdentityRequest\x1a$.api.v1.build.settings.BuildSettings\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/app/{name}/build/settings\x12\x95\x01\n" +
	"\x12ApplyBuildSettings\x120.api.v1.build.settings.ApplyBuildSettingsRequest\x1a\x16.google.protobuf.Empty\"5\x82\xd3\xe4\x93\x02/:\x0ebuild_settings\"\x1d/v1/app/{name}/build/settingsB+Z)api-server/api/v1/build/settings;settingsb\x06proto3"

var (
	file_v1_build_settings_build_settings_proto_rawDescOnce sync.Once
	file_v1_build_settings_build_settings_proto_rawDescData []byte
)

func file_v1_build_settings_build_settings_proto_rawDescGZIP() []byte {
	file_v1_build_settings_build_settings_proto_rawDescOnce.Do(func() {
		file_v1_build_settings_build_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_build_settings_build_settings_proto_rawDesc), len(file_v1_build_settings_build_settings_proto_rawDesc)))
	})
	return file_v1_build_settings_build_settings_proto_rawDescData
}

var file_v1_build_settings_build_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_build_settings_build_settings_proto_goTypes = []any{
	(*BuildSettings)(nil),               // 0: api.v1.build.settings.BuildSettings
	(*ApplyBuildSettingsRequest)(nil),   // 1: api.v1.build.settings.ApplyBuildSettingsRequest
	(*BuildSettings_GitSettings)(nil),   // 2: api.v1.build.settings.BuildSettings.GitSettings
	(*BuildSettings_ImageSettings)(nil), // 3: api.v1.build.settings.BuildSettings.ImageSettings
	(*application.IdentityRequest)(nil), // 4: api.v1.application.IdentityRequest
	(*emptypb.Empty)(nil),               // 5: google.protobuf.Empty
}
var file_v1_build_settings_build_settings_proto_depIdxs = []int32{
	2, // 0: api.v1.build.settings.BuildSettings.git:type_name -> api.v1.build.settings.BuildSettings.GitSettings
	3, // 1: api.v1.build.settings.BuildSettings.image:type_name -> api.v1.build.settings.BuildSettings.ImageSettings
	0, // 2: api.v1.build.settings.ApplyBuildSettingsRequest.build_settings:type_name -> api.v1.build.settings.BuildSettings
	4, // 3: api.v1.build.settings.BuildSettingsService.GetBuildSettings:input_type -> api.v1.application.IdentityRequest
	1, // 4: api.v1.build.settings.BuildSettingsService.ApplyBuildSettings:input_type -> api.v1.build.settings.ApplyBuildSettingsRequest
	0, // 5: api.v1.build.settings.BuildSettingsService.GetBuildSettings:output_type -> api.v1.build.settings.BuildSettings
	5, // 6: api.v1.build.settings.BuildSettingsService.ApplyBuildSettings:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_build_settings_build_settings_proto_init() }
func file_v1_build_settings_build_settings_proto_init() {
	if File_v1_build_settings_build_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_build_settings_build_settings_proto_rawDesc), len(file_v1_build_settings_build_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_build_settings_build_settings_proto_goTypes,
		DependencyIndexes: file_v1_build_settings_build_settings_proto_depIdxs,
		MessageInfos:      file_v1_build_settings_build_settings_proto_msgTypes,
	}.Build()
	File_v1_build_settings_build_settings_proto = out.File
	file_v1_build_settings_build_settings_proto_goTypes = nil
	file_v1_build_settings_build_settings_proto_depIdxs = nil
}
