// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: v1/cluster/cluster.proto

package cluster

import (
	common "api-server/api/v1/common"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connection_Type int32

const (
	Connection_UNSPECIFIED Connection_Type = 0
	Connection_NONE        Connection_Type = 1
	Connection_TLS_CERT    Connection_Type = 2
	Connection_TLS_TOKEN   Connection_Type = 3
)

// Enum value maps for Connection_Type.
var (
	Connection_Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NONE",
		2: "TLS_CERT",
		3: "TLS_TOKEN",
	}
	Connection_Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NONE":        1,
		"TLS_CERT":    2,
		"TLS_TOKEN":   3,
	}
)

func (x Connection_Type) Enum() *Connection_Type {
	p := new(Connection_Type)
	*p = x
	return p
}

func (x Connection_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Connection_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_cluster_cluster_proto_enumTypes[0].Descriptor()
}

func (Connection_Type) Type() protoreflect.EnumType {
	return &file_v1_cluster_cluster_proto_enumTypes[0]
}

func (x Connection_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Connection_Type.Descriptor instead.
func (Connection_Type) EnumDescriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{0, 0}
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Ca            string                 `protobuf:"bytes,2,opt,name=ca,proto3" json:"ca,omitempty"`
	Type          Connection_Type        `protobuf:"varint,3,opt,name=type,proto3,enum=api.v1.cluster.Connection_Type" json:"type,omitempty"`
	Cert          string                 `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Connection) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

func (x *Connection) GetType() Connection_Type {
	if x != nil {
		return x.Type
	}
	return Connection_UNSPECIFIED
}

func (x *Connection) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *Connection) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Connection) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Connection    *Connection            `protobuf:"bytes,5,opt,name=connection,proto3" json:"connection,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *Cluster) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cluster) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *Cluster) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cluster) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.Page           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ListClustersRequest) GetPage() *common.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *common.Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items         []*Cluster             `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ListClustersResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListClustersResponse) GetItems() []*Cluster {
	if x != nil {
		return x.Items
	}
	return nil
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *IdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResolveKubeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKubeConfigRequest) Reset() {
	*x = ResolveKubeConfigRequest{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKubeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKubeConfigRequest) ProtoMessage() {}

func (x *ResolveKubeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKubeConfigRequest.ProtoReflect.Descriptor instead.
func (*ResolveKubeConfigRequest) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveKubeConfigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ResolveKubeConfigResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Items         []*ResolveKubeConfigResponse_Context `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKubeConfigResponse) Reset() {
	*x = ResolveKubeConfigResponse{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKubeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKubeConfigResponse) ProtoMessage() {}

func (x *ResolveKubeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKubeConfigResponse.ProtoReflect.Descriptor instead.
func (*ResolveKubeConfigResponse) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveKubeConfigResponse) GetItems() []*ResolveKubeConfigResponse_Context {
	if x != nil {
		return x.Items
	}
	return nil
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *TestConnectionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TestOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestOperatorResponse) Reset() {
	*x = TestOperatorResponse{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOperatorResponse) ProtoMessage() {}

func (x *TestOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOperatorResponse.ProtoReflect.Descriptor instead.
func (*TestOperatorResponse) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{8}
}

type ResolveKubeConfigResponse_Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Ca            string                 `protobuf:"bytes,2,opt,name=ca,proto3" json:"ca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKubeConfigResponse_Cluster) Reset() {
	*x = ResolveKubeConfigResponse_Cluster{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKubeConfigResponse_Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKubeConfigResponse_Cluster) ProtoMessage() {}

func (x *ResolveKubeConfigResponse_Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKubeConfigResponse_Cluster.ProtoReflect.Descriptor instead.
func (*ResolveKubeConfigResponse_Cluster) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ResolveKubeConfigResponse_Cluster) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ResolveKubeConfigResponse_Cluster) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

type ResolveKubeConfigResponse_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          string                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKubeConfigResponse_User) Reset() {
	*x = ResolveKubeConfigResponse_User{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKubeConfigResponse_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKubeConfigResponse_User) ProtoMessage() {}

func (x *ResolveKubeConfigResponse_User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKubeConfigResponse_User.ProtoReflect.Descriptor instead.
func (*ResolveKubeConfigResponse_User) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{6, 1}
}

func (x *ResolveKubeConfigResponse_User) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *ResolveKubeConfigResponse_User) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ResolveKubeConfigResponse_Context struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Name          string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Current       bool                               `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	Cluster       *ResolveKubeConfigResponse_Cluster `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	User          *ResolveKubeConfigResponse_User    `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKubeConfigResponse_Context) Reset() {
	*x = ResolveKubeConfigResponse_Context{}
	mi := &file_v1_cluster_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKubeConfigResponse_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKubeConfigResponse_Context) ProtoMessage() {}

func (x *ResolveKubeConfigResponse_Context) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cluster_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKubeConfigResponse_Context.ProtoReflect.Descriptor instead.
func (*ResolveKubeConfigResponse_Context) Descriptor() ([]byte, []int) {
	return file_v1_cluster_cluster_proto_rawDescGZIP(), []int{6, 2}
}

func (x *ResolveKubeConfigResponse_Context) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveKubeConfigResponse_Context) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResolveKubeConfigResponse_Context) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

func (x *ResolveKubeConfigResponse_Context) GetCluster() *ResolveKubeConfigResponse_Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *ResolveKubeConfigResponse_Context) GetUser() *ResolveKubeConfigResponse_User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_v1_cluster_cluster_proto protoreflect.FileDescriptor

const file_v1_cluster_cluster_proto_rawDesc = "" +
	"\n" +
	"\x18v1/cluster/cluster.proto\x12\x0eapi.v1.cluster\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a\x14v1/common/page.proto\"\x86\x02\n" +
	"\n" +
	"Connection\x12)\n" +
	"\aaddress\x18\x01 \x01(\tB\x0f\xe2A\x01\x02\xfaB\br\x06\x18\x80\x04\x88\x01\x01R\aaddress\x12\x0e\n" +
	"\x02ca\x18\x02 \x01(\tR\x02ca\x12A\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.api.v1.cluster.Connection.TypeB\f\xe2A\x01\x02\xfaB\x05\x82\x01\x02 \x00R\x04type\x12\x12\n" +
	"\x04cert\x18\x04 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\">\n" +
	"\x04Type\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\f\n" +
	"\bTLS_CERT\x10\x02\x12\r\n" +
	"\tTLS_TOKEN\x10\x03\"\xd8\x02\n" +
	"\aCluster\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x04B\x04\xe2A\x01\x05R\x02id\x12C\n" +
	"\x04name\x18\x02 \x01(\tB/\xe2A\x01\x02\xfaB(r&\x18@2\"^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$R\x04name\x12.\n" +
	"\vdescription\x18\x03 \x01(\tB\f\xe2A\x01\x01\xfaB\x05r\x03\x18\x80\bR\vdescription\x12@\n" +
	"\n" +
	"connection\x18\x05 \x01(\v2\x1a.api.v1.cluster.ConnectionB\x04\xe2A\x01\x02R\n" +
	"connection\x12?\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\tcreatedAt\x12?\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\tupdatedAt\">\n" +
	"\x13ListClustersRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.api.v1.common.PageR\x04page\"\x80\x01\n" +
	"\x14ListClustersResponse\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.api.v1.common.PaginationR\n" +
	"pagination\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.api.v1.cluster.ClusterR\x05items\"!\n" +
	"\tIdRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x04B\x04\xe2A\x01\x02R\x02id\":\n" +
	"\x18ResolveKubeConfigRequest\x12\x1e\n" +
	"\acontent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\acontent\"\xbc\x03\n" +
	"\x19ResolveKubeConfigResponse\x12G\n" +
	"\x05items\x18\x01 \x03(\v21.api.v1.cluster.ResolveKubeConfigResponse.ContextR\x05items\x1a?\n" +
	"\aCluster\x12$\n" +
	"\x06server\x18\x01 \x01(\tB\f\xe2A\x01\x02\xfaB\x05r\x03\x88\x01\x01R\x06server\x12\x0e\n" +
	"\x02ca\x18\x02 \x01(\tR\x02ca\x1a,\n" +
	"\x04User\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x1a\xe6\x01\n" +
	"\aContext\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\bR\acurrent\x12K\n" +
	"\acluster\x18\x04 \x01(\v21.api.v1.cluster.ResolveKubeConfigResponse.ClusterR\acluster\x12B\n" +
	"\x04user\x18\x05 \x01(\v2..api.v1.cluster.ResolveKubeConfigResponse.UserR\x04user\"2\n" +
	"\x16TestConnectionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x16\n" +
	"\x14TestOperatorResponse2\x99\a\n" +
	"\x0eClusterService\x12r\n" +
	"\fListClusters\x12#.api.v1.cluster.ListClustersRequest\x1a$.api.v1.cluster.ListClustersResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/cluster\x12^\n" +
	"\n" +
	"GetCluster\x12\x19.api.v1.cluster.IdRequest\x1a\x17.api.v1.cluster.Cluster\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/cluster/{id}\x12\\\n" +
	"\rCreateCluster\x12\x17.api.v1.cluster.Cluster\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/cluster\x12a\n" +
	"\rUpdateCluster\x12\x17.api.v1.cluster.Cluster\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/cluster/{id}\x12`\n" +
	"\rDeleteCluster\x12\x19.api.v1.cluster.IdRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/cluster/{id}\x12\x90\x01\n" +
	"\x11ResolveKubeConfig\x12(.api.v1.cluster.ResolveKubeConfigRequest\x1a).api.v1.cluster.ResolveKubeConfigResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/cluster/kube/config\x12\x80\x01\n" +
	"\x0eTestConnection\x12\x1a.api.v1.cluster.Connection\x1a&.api.v1.cluster.TestConnectionResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/cluster/connection/test\x12z\n" +
	"\fTestOperator\x12\x1a.api.v1.cluster.Connection\x1a$.api.v1.cluster.TestOperatorResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/cluster/operator/testB#Z!api-server/api/v1/cluster;clusterb\x06proto3"

var (
	file_v1_cluster_cluster_proto_rawDescOnce sync.Once
	file_v1_cluster_cluster_proto_rawDescData []byte
)

func file_v1_cluster_cluster_proto_rawDescGZIP() []byte {
	file_v1_cluster_cluster_proto_rawDescOnce.Do(func() {
		file_v1_cluster_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_cluster_cluster_proto_rawDesc), len(file_v1_cluster_cluster_proto_rawDesc)))
	})
	return file_v1_cluster_cluster_proto_rawDescData
}

var file_v1_cluster_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_cluster_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_cluster_cluster_proto_goTypes = []any{
	(Connection_Type)(0),                      // 0: api.v1.cluster.Connection.Type
	(*Connection)(nil),                        // 1: api.v1.cluster.Connection
	(*Cluster)(nil),                           // 2: api.v1.cluster.Cluster
	(*ListClustersRequest)(nil),               // 3: api.v1.cluster.ListClustersRequest
	(*ListClustersResponse)(nil),              // 4: api.v1.cluster.ListClustersResponse
	(*IdRequest)(nil),                         // 5: api.v1.cluster.IdRequest
	(*ResolveKubeConfigRequest)(nil),          // 6: api.v1.cluster.ResolveKubeConfigRequest
	(*ResolveKubeConfigResponse)(nil),         // 7: api.v1.cluster.ResolveKubeConfigResponse
	(*TestConnectionResponse)(nil),            // 8: api.v1.cluster.TestConnectionResponse
	(*TestOperatorResponse)(nil),              // 9: api.v1.cluster.TestOperatorResponse
	(*ResolveKubeConfigResponse_Cluster)(nil), // 10: api.v1.cluster.ResolveKubeConfigResponse.Cluster
	(*ResolveKubeConfigResponse_User)(nil),    // 11: api.v1.cluster.ResolveKubeConfigResponse.User
	(*ResolveKubeConfigResponse_Context)(nil), // 12: api.v1.cluster.ResolveKubeConfigResponse.Context
	(*timestamppb.Timestamp)(nil),             // 13: google.protobuf.Timestamp
	(*common.Page)(nil),                       // 14: api.v1.common.Page
	(*common.Pagination)(nil),                 // 15: api.v1.common.Pagination
	(*emptypb.Empty)(nil),                     // 16: google.protobuf.Empty
}
var file_v1_cluster_cluster_proto_depIdxs = []int32{
	0,  // 0: api.v1.cluster.Connection.type:type_name -> api.v1.cluster.Connection.Type
	1,  // 1: api.v1.cluster.Cluster.connection:type_name -> api.v1.cluster.Connection
	13, // 2: api.v1.cluster.Cluster.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: api.v1.cluster.Cluster.updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: api.v1.cluster.ListClustersRequest.page:type_name -> api.v1.common.Page
	15, // 5: api.v1.cluster.ListClustersResponse.pagination:type_name -> api.v1.common.Pagination
	2,  // 6: api.v1.cluster.ListClustersResponse.items:type_name -> api.v1.cluster.Cluster
	12, // 7: api.v1.cluster.ResolveKubeConfigResponse.items:type_name -> api.v1.cluster.ResolveKubeConfigResponse.Context
	10, // 8: api.v1.cluster.ResolveKubeConfigResponse.Context.cluster:type_name -> api.v1.cluster.ResolveKubeConfigResponse.Cluster
	11, // 9: api.v1.cluster.ResolveKubeConfigResponse.Context.user:type_name -> api.v1.cluster.ResolveKubeConfigResponse.User
	3,  // 10: api.v1.cluster.ClusterService.ListClusters:input_type -> api.v1.cluster.ListClustersRequest
	5,  // 11: api.v1.cluster.ClusterService.GetCluster:input_type -> api.v1.cluster.IdRequest
	2,  // 12: api.v1.cluster.ClusterService.CreateCluster:input_type -> api.v1.cluster.Cluster
	2,  // 13: api.v1.cluster.ClusterService.UpdateCluster:input_type -> api.v1.cluster.Cluster
	5,  // 14: api.v1.cluster.ClusterService.DeleteCluster:input_type -> api.v1.cluster.IdRequest
	6,  // 15: api.v1.cluster.ClusterService.ResolveKubeConfig:input_type -> api.v1.cluster.ResolveKubeConfigRequest
	1,  // 16: api.v1.cluster.ClusterService.TestConnection:input_type -> api.v1.cluster.Connection
	1,  // 17: api.v1.cluster.ClusterService.TestOperator:input_type -> api.v1.cluster.Connection
	4,  // 18: api.v1.cluster.ClusterService.ListClusters:output_type -> api.v1.cluster.ListClustersResponse
	2,  // 19: api.v1.cluster.ClusterService.GetCluster:output_type -> api.v1.cluster.Cluster
	16, // 20: api.v1.cluster.ClusterService.CreateCluster:output_type -> google.protobuf.Empty
	16, // 21: api.v1.cluster.ClusterService.UpdateCluster:output_type -> google.protobuf.Empty
	16, // 22: api.v1.cluster.ClusterService.DeleteCluster:output_type -> google.protobuf.Empty
	7,  // 23: api.v1.cluster.ClusterService.ResolveKubeConfig:output_type -> api.v1.cluster.ResolveKubeConfigResponse
	8,  // 24: api.v1.cluster.ClusterService.TestConnection:output_type -> api.v1.cluster.TestConnectionResponse
	9,  // 25: api.v1.cluster.ClusterService.TestOperator:output_type -> api.v1.cluster.TestOperatorResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_cluster_cluster_proto_init() }
func file_v1_cluster_cluster_proto_init() {
	if File_v1_cluster_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_cluster_cluster_proto_rawDesc), len(file_v1_cluster_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_cluster_cluster_proto_goTypes,
		DependencyIndexes: file_v1_cluster_cluster_proto_depIdxs,
		EnumInfos:         file_v1_cluster_cluster_proto_enumTypes,
		MessageInfos:      file_v1_cluster_cluster_proto_msgTypes,
	}.Build()
	File_v1_cluster_cluster_proto = out.File
	file_v1_cluster_cluster_proto_goTypes = nil
	file_v1_cluster_cluster_proto_depIdxs = nil
}
