/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "api-server/internal/kube2/apis/application/v1"
	applicationv1 "api-server/internal/kube2/applyconfiguration/application/v1"
	typedapplicationv1 "api-server/internal/kube2/clientset/versioned/typed/application/v1"
	context "context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
)

// fakeApplications implements ApplicationInterface
type fakeApplications struct {
	*gentype.FakeClientWithListAndApply[*v1.Application, *v1.ApplicationList, *applicationv1.ApplicationApplyConfiguration]
	Fake *FakeKubelandV1
}

func newFakeApplications(fake *FakeKubelandV1, namespace string) typedapplicationv1.ApplicationInterface {
	return &fakeApplications{
		gentype.NewFakeClientWithListAndApply[*v1.Application, *v1.ApplicationList, *applicationv1.ApplicationApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("applications"),
			v1.SchemeGroupVersion.WithKind("Application"),
			func() *v1.Application { return &v1.Application{} },
			func() *v1.ApplicationList { return &v1.ApplicationList{} },
			func(dst, src *v1.ApplicationList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ApplicationList) []*v1.Application { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ApplicationList, items []*v1.Application) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}

// GetApplication takes name of the application, and returns the corresponding application object, and an error if there is any.
func (c *fakeApplications) GetApplication(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Application, err error) {
	emptyResult := &v1.Application{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(c.Resource(), c.Namespace(), name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Application), err
}
